const fs = require('fs');
const path = require('path');

const aliases = `
export const getEquipments = getAssetsMasters;
export const createEquipment = createEquipmentEquipments;
export const deleteEquipment = deleteEquipmentEquipmentsById;
export const createEquipmentCategory = createEquipmentCategories;
export const getEquipmentMaintenanceSchedules = getEquipmentMaintenanceschedules;
export const createEquipmentMaintenanceSchedule = createEquipmentMaintenanceschedules;
export const getEquipmentMaintenanceLogs = getEquipmentMaintenancelogs;
export const getEquipmentCalibrationRecords = getEquipmentCalibrationrecords;
export const getEquipmentSpareParts = getEquipmentSpareparts;
export const getEquipmentUsageLogs = getEquipmentUsagelogs;
export const getEquipmentBreakdowns = async () => ({ data: [], status: 200, ok: true });
export const createEquipmentBreakdown = async () => ({ data: null, status: 200, ok: true });

export const getPharmacyDispenses = async () => ({ data: [], status: 200, ok: true });
export const createPharmacyDispense = async () => ({ data: null, status: 200, ok: true });
export const listMedicines = async () => ({ data: [], status: 200, ok: true });
export const createMedicine = async () => ({ data: null, status: 200, ok: true });
export const getPharmacyInvoices = async () => ({ data: [], status: 200, ok: true });
export const createPharmacyInvoice = async () => ({ data: null, status: 200, ok: true });
export const getPharmacyStocks = async () => ({ data: [], status: 200, ok: true });
export const createPharmacyStock = async () => ({ data: null, status: 200, ok: true });
export const getPharmacySuppliers = async () => ({ data: [], status: 200, ok: true });
export const createPharmacySupplier = async () => ({ data: null, status: 200, ok: true });
export const getPurchaseOrders = async () => ({ data: [], status: 200, ok: true });
export const getGRNs = async () => ({ data: [], status: 200, ok: true });
export const getInsuranceClaims = async () => ({ data: [], status: 200, ok: true });
export const getStockTransfers = async () => ({ data: [], status: 200, ok: true });
export const getStockAdjustments = async () => ({ data: [], status: 200, ok: true });
export const getPharmacyPrescriptions = async () => ({ data: [], status: 200, ok: true });

export const patientRegister = createPatientsRegister;
export const listPatients = async () => ({ data: [], status: 200, ok: true });

export const listCertificateTypes = async () => ({ data: [], status: 200, ok: true });
export const listCertificateTemplates = async () => ({ data: [], status: 200, ok: true });
export const listGeneratedCertificates = async () => ({ data: [], status: 200, ok: true });
export const createGeneratedCertificate = async () => ({ data: null, status: 200, ok: true });
export const updateCertificateTemplate = async () => ({ data: null, status: 200, ok: true });
export const createCertificateTemplate = async () => ({ data: null, status: 200, ok: true });
export const deleteCertificateTemplate = async () => ({ data: null, status: 200, ok: true });
export const listDoctors = async () => ({ data: [], status: 200, ok: true });
export const listCertificateSignatures = async () => ({ data: [], status: 200, ok: true });
export const createCertificateSignature = async () => ({ data: null, status: 200, ok: true });
export const updateCertificateSignature = async () => ({ data: null, status: 200, ok: true });
export const deleteCertificateSignature = async () => ({ data: null, status: 200, ok: true });
export const listCertificateVerifications = async () => ({ data: [], status: 200, ok: true });
export const verifyCertificate = async () => ({ data: null, status: 200, ok: true });

export const listAmbulances = async () => ({ data: [], status: 200, ok: true });
export const createAmbulance = async () => ({ data: null, status: 200, ok: true });
export const updateAmbulance = async () => ({ data: null, status: 200, ok: true });
export const deleteAmbulance = async () => ({ data: null, status: 200, ok: true });
export const listAmbulanceTrips = async () => ({ data: [], status: 200, ok: true });
export const createAmbulanceTrip = async () => ({ data: null, status: 200, ok: true });
export const listAmbulanceMaintenances = async () => ({ data: [], status: 200, ok: true });
export const createAmbulanceMaintenance = async () => ({ data: null, status: 200, ok: true });
export const listUsers = async () => ({ data: [], status: 200, ok: true });

export const listBloodInventory = async () => ({ data: [], status: 200, ok: true });
export const listBloodRequests = async () => ({ data: [], status: 200, ok: true });
export const listBloodDonors = async () => ({ data: [], status: 200, ok: true });
export const listBloodDonations = async () => ({ data: [], status: 200, ok: true });
export const listBloodGroups = async () => ({ data: [], status: 200, ok: true });
export const listBloodComponents = async () => ({ data: [], status: 200, ok: true });
export const createBloodRequest = async () => ({ data: null, status: 200, ok: true });
export const updateBloodRequestStatus = async () => ({ data: null, status: 200, ok: true });
export const createBloodDonor = async () => ({ data: null, status: 200, ok: true });
export const createBloodDonation = async () => ({ data: null, status: 200, ok: true });
export const issueBlood = async () => ({ data: null, status: 200, ok: true });
export const updateBloodDonor = async () => ({ data: null, status: 200, ok: true });
export const deleteBloodDonor = async () => ({ data: null, status: 200, ok: true });
export const updateBloodRequest = async () => ({ data: null, status: 200, ok: true });
export const deleteBloodRequest = async () => ({ data: null, status: 200, ok: true });
export const updateBloodInventoryStatus = async () => ({ data: null, status: 200, ok: true });
export const deleteBloodInventory = async () => ({ data: null, status: 200, ok: true });
export const createBloodComponent = async () => ({ data: null, status: 200, ok: true });
export const createBloodInventory = async () => ({ data: null, status: 200, ok: true });

export const getAutoGeoCountries = async () => ({ data: [], status: 200, ok: true });
export const createLogin = async () => ({ data: [], status: 200, ok: true });
export const getAutoDashboardDoctor = async () => ({ data: [], status: 200, ok: true });
export const getDashboardStats = async () => ({ data: [], status: 200, ok: true });
export const getAutoAdminUsers = async () => ({ data: [], status: 200, ok: true });
export const getAutoClinicals = async () => ({ data: [], status: 200, ok: true });
export const getAutoAssetsMasters = async () => ({ data: [], status: 200, ok: true });
export const getAutoAdminBranches = async () => ({ data: [], status: 200, ok: true });
export const getAutoIpdBeds = async () => ({ data: [], status: 200, ok: true });
export const getAutoBillingInvoicesSearch = async () => ({ data: [], status: 200, ok: true });
export const extractArray = async () => ({ data: [], status: 200, ok: true });
export const searchPatients = async () => ({ data: [], status: 200, ok: true });
export const getAutoUsers = async () => ({ data: [], status: 200, ok: true });
export const updateById = async () => ({ data: [], status: 200, ok: true });
export const createAutoClinical = async () => ({ data: [], status: 200, ok: true });
export const updateAppointmentStatus = async () => ({ data: [], status: 200, ok: true });
export const getOPDVisits = async () => ({ data: [], status: 200, ok: true });
export const getAutoEquipmentLocations = async () => ({ data: [], status: 200, ok: true });
export const getAutoDepartments = async () => ({ data: [], status: 200, ok: true });
export const getAppointments = async () => ({ data: [], status: 200, ok: true });
`;

const apiPath = path.join(__dirname, 'src', 'api', 'apiService.ts');
fs.appendFileSync(apiPath, aliases);
console.log('Aliases added successfully');
