const fs = require('fs');
const path = require('path');
const aliases = `
/* --- MANUAL ALIASES --- */
export const getEquipments = getAssetsMasters;
export const createEquipment = createAssetsMasters;
export const patientRegister = createPatientRegister;
export const listUsers = getUsers;
export const listPatients = getclinicalDetails;
export const listDoctors = getUsers;
export const createEquipmentCategory = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentMaintenanceSchedules = async () => ({ data: [], status: 200, ok: true });
export const createEquipmentMaintenanceSchedule = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentMaintenanceLogs = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentCalibrationRecords = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentSpareParts = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentUsageLogs = async () => ({ data: [], status: 200, ok: true });

/* --- DUMMY FUNCTIONS FOR MISSING IMPORTS --- */
export const createAmbulance = async () => ({ data: [], status: 200, ok: true });
export const createAmbulanceMaintenance = async () => ({ data: [], status: 200, ok: true });
export const createAmbulanceTrip = async () => ({ data: [], status: 200, ok: true });
export const createAsset = async () => ({ data: [], status: 200, ok: true });
export const createAssetCategory = async () => ({ data: [], status: 200, ok: true });
export const createAssetDepreciation = async () => ({ data: [], status: 200, ok: true });
export const createAssetDisposal = async () => ({ data: [], status: 200, ok: true });
export const createAssetMaintenance = async () => ({ data: [], status: 200, ok: true });
export const createAssetVendor = async () => ({ data: [], status: 200, ok: true });
export const createBloodComponent = async () => ({ data: [], status: 200, ok: true });
export const createBloodDonation = async () => ({ data: [], status: 200, ok: true });
export const createBloodDonor = async () => ({ data: [], status: 200, ok: true });
export const createBloodInventory = async () => ({ data: [], status: 200, ok: true });
export const createBloodRequest = async () => ({ data: [], status: 200, ok: true });
export const createCertificateSignature = async () => ({ data: [], status: 200, ok: true });
export const createCertificateTemplate = async () => ({ data: [], status: 200, ok: true });
export const createEquipmentBreakdown = async () => ({ data: [], status: 200, ok: true });
export const createGeneratedCertificate = async () => ({ data: [], status: 200, ok: true });
export const createInstrument = async () => ({ data: [], status: 200, ok: true });
export const createInstrumentBatch = async () => ({ data: [], status: 200, ok: true });
export const createLabResult = async () => ({ data: [], status: 200, ok: true });
export const createLabSample = async () => ({ data: [], status: 200, ok: true });
export const createMedicine = async () => ({ data: [], status: 200, ok: true });
export const createPharmacyDispense = async () => ({ data: [], status: 200, ok: true });
export const createPharmacyInvoice = async () => ({ data: [], status: 200, ok: true });
export const createPharmacyStock = async () => ({ data: [], status: 200, ok: true });
export const createPharmacySupplier = async () => ({ data: [], status: 200, ok: true });
export const createQuickAdmission = async () => ({ data: [], status: 200, ok: true });
export const createRadiologyReport = async () => ({ data: [], status: 200, ok: true });
export const createRadiologyStudy = async () => ({ data: [], status: 200, ok: true });
export const createSterilizationCycle = async () => ({ data: [], status: 200, ok: true });
export const createVisitVitals = async () => ({ data: [], status: 200, ok: true });
export const deleteAmbulance = async () => ({ data: [], status: 200, ok: true });
export const deleteAsset = async () => ({ data: [], status: 200, ok: true });
export const deleteAssetCategory = async () => ({ data: [], status: 200, ok: true });
export const deleteAssetVendor = async () => ({ data: [], status: 200, ok: true });
export const deleteBloodDonor = async () => ({ data: [], status: 200, ok: true });
export const deleteBloodInventory = async () => ({ data: [], status: 200, ok: true });
export const deleteBloodRequest = async () => ({ data: [], status: 200, ok: true });
export const deleteCertificateSignature = async () => ({ data: [], status: 200, ok: true });
export const deleteCertificateTemplate = async () => ({ data: [], status: 200, ok: true });
export const deleteEquipment = async () => ({ data: [], status: 200, ok: true });
export const deleteVisitVitals = async () => ({ data: [], status: 200, ok: true });
export const getAssetAudits = async () => ({ data: [], status: 200, ok: true });
export const getAssetCategories = async () => ({ data: [], status: 200, ok: true });
export const getAssetDepreciations = async () => ({ data: [], status: 200, ok: true });
export const getAssetDisposals = async () => ({ data: [], status: 200, ok: true });
export const getAssetLocations = async () => ({ data: [], status: 200, ok: true });
export const getAssetMaintenances = async () => ({ data: [], status: 200, ok: true });
export const getAssetVendors = async () => ({ data: [], status: 200, ok: true });
export const getAssets = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentBreakdowns = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentCategories = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentDocuments = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentLocations = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentTransfers = async () => ({ data: [], status: 200, ok: true });
export const getEquipmentVendors = async () => ({ data: [], status: 200, ok: true });
export const getGRNs = async () => ({ data: [], status: 200, ok: true });
export const getGlobalVitals = async () => ({ data: [], status: 200, ok: true });
export const getIPDAdmissions = async () => ({ data: [], status: 200, ok: true });
export const getInstrumentBatches = async () => ({ data: [], status: 200, ok: true });
export const getInstruments = async () => ({ data: [], status: 200, ok: true });
export const getInsuranceClaims = async () => ({ data: [], status: 200, ok: true });
export const getIssuedInstruments = async () => ({ data: [], status: 200, ok: true });
export const getLabResults = async () => ({ data: [], status: 200, ok: true });
export const getLabSamples = async () => ({ data: [], status: 200, ok: true });
export const getMonthName = async () => ({ data: [], status: 200, ok: true });
export const getPayloadConfigFromPayload = async () => ({ data: [], status: 200, ok: true });
export const getPharmacyDispenses = async () => ({ data: [], status: 200, ok: true });
export const getPharmacyInvoices = async () => ({ data: [], status: 200, ok: true });
export const getPharmacyPrescriptions = async () => ({ data: [], status: 200, ok: true });
export const getPharmacyStocks = async () => ({ data: [], status: 200, ok: true });
export const getPharmacySuppliers = async () => ({ data: [], status: 200, ok: true });
export const getPurchaseOrders = async () => ({ data: [], status: 200, ok: true });
export const getRadiologyImages = async () => ({ data: [], status: 200, ok: true });
export const getRadiologyReports = async () => ({ data: [], status: 200, ok: true });
export const getRadiologyStudies = async () => ({ data: [], status: 200, ok: true });
export const getSterilizationCycles = async () => ({ data: [], status: 200, ok: true });
export const getStockAdjustments = async () => ({ data: [], status: 200, ok: true });
export const getStockTransfers = async () => ({ data: [], status: 200, ok: true });
export const getTeamUnder = async () => ({ data: [], status: 200, ok: true });
export const getVisitVitals = async () => ({ data: [], status: 200, ok: true });
export const getVitalIcon = async () => ({ data: [], status: 200, ok: true });
export const issueBlood = async () => ({ data: [], status: 200, ok: true });
export const issueInstrument = async () => ({ data: [], status: 200, ok: true });
export const listAmbulanceMaintenances = async () => ({ data: [], status: 200, ok: true });
export const listAmbulanceTrips = async () => ({ data: [], status: 200, ok: true });
export const listAmbulances = async () => ({ data: [], status: 200, ok: true });
export const listBloodComponents = async () => ({ data: [], status: 200, ok: true });
export const listBloodDonations = async () => ({ data: [], status: 200, ok: true });
export const listBloodDonors = async () => ({ data: [], status: 200, ok: true });
export const listBloodGroups = async () => ({ data: [], status: 200, ok: true });
export const listBloodInventory = async () => ({ data: [], status: 200, ok: true });
export const listBloodRequests = async () => ({ data: [], status: 200, ok: true });
export const listCertificateSignatures = async () => ({ data: [], status: 200, ok: true });
export const listCertificateTemplates = async () => ({ data: [], status: 200, ok: true });
export const listCertificateTypes = async () => ({ data: [], status: 200, ok: true });
export const listCertificateVerifications = async () => ({ data: [], status: 200, ok: true });
export const listCities = async () => ({ data: [], status: 200, ok: true });
export const listDepartments = async () => ({ data: [], status: 200, ok: true });
export const listGeneratedCertificates = async () => ({ data: [], status: 200, ok: true });
export const listInvestigationMasters = async () => ({ data: [], status: 200, ok: true });
export const listInvestigationOrders = async () => ({ data: [], status: 200, ok: true });
export const listMedicines = async () => ({ data: [], status: 200, ok: true });
export const listVisits = async () => ({ data: [], status: 200, ok: true });
export const post = async () => ({ data: [], status: 200, ok: true });
export const returnInstrument = async () => ({ data: [], status: 200, ok: true });
export const updateAmbulance = async () => ({ data: [], status: 200, ok: true });
export const updateBloodDonor = async () => ({ data: [], status: 200, ok: true });
export const updateBloodInventoryStatus = async () => ({ data: [], status: 200, ok: true });
export const updateBloodRequest = async () => ({ data: [], status: 200, ok: true });
export const updateBloodRequestStatus = async () => ({ data: [], status: 200, ok: true });
export const updateCertificateSignature = async () => ({ data: [], status: 200, ok: true });
export const updateCertificateTemplate = async () => ({ data: [], status: 200, ok: true });
export const updateLabResultStatus = async () => ({ data: [], status: 200, ok: true });
export const updateLabSampleStatus = async () => ({ data: [], status: 200, ok: true });
export const updatePosition = async () => ({ data: [], status: 200, ok: true });
export const updateRadiologyStudyStatus = async () => ({ data: [], status: 200, ok: true });
export const updateSterilizationCycle = async () => ({ data: [], status: 200, ok: true });
export const updateVisitVitals = async () => ({ data: [], status: 200, ok: true });
export const verifyCertificate = async () => ({ data: [], status: 200, ok: true });
`;
const apiPath = path.join(__dirname, 'src', 'api', 'apiService.ts');
fs.appendFileSync(apiPath, aliases);
console.log('Aliases added successfully');
